/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author bruno
 */
public class TelaSobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaSobre
     */
    public TelaSobre() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sobre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 30, 100, 40);

        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<html>\n<center>O SGE (Sistema de Gerenciamento Educacional), surgiu com o intuito de sanar alguns <br><p>\ndos problemas de armazenamento de uma das filiais da escola de <br>\ncursos profissionalizantes Logus informática, situada em cotia. <br>\nA oportunidade de desenvolver o projeto apareceu por meio de uma proposta de um dos integrantes do grupo,\n que trabalhava na escola, vendo que a escola ainda armazenava registros importantes dos alunos de forma física,\n o que foi analisado como arcaico em vista do da importância dessas mesmas documentações. <br><br></center>\n\n<font face=\"Calibrini\" size =\"5\">\n<u><br>\nFerramentas do Sistema:</u></font><br>\n\nInterface interativa com o usuário;<br>\nCadastro de Funcionários (Professores e Administração);<br>\nCadastro de Alunos;<br>\nGerador de Relatórios;<br>\nGerador de chamadas;<br>\nServiços especializados de Funcionários comuns e Usuários administradores. <br>\n\n<br><br>\nDesenvolvedores: Bruno Figueiredo Sousa, Lucas Luiz dos Santos, Rodrigo Leite do Sacramento.\n\n</html>\n"); // NOI18N
        jButton1.setActionCommand("<html>\nO SGE (Sistema de Gerenciamento Educacional), surgiu com o intuito de sanar alguns dos problemas de armazenamento de uma das filiais da escola de cursos\n profissionalizantes Logus informática, situada em cotia. \nA oportunidade de desenvolver o projeto apareceu por meio de uma proposta de um dos integrantes do grupo,\n que trabalhava na escola, vendo que a escola ainda armazenava registros importantes dos alunos de forma física,\n o que foi analisado como arcaico em vista do da importância dessas mesmas documentações. \n\nFerramentas do Sistema:\n\nInterface interativa com o usuário;\nCadastro de Funcionários (Professores e Administração);\nCadastro de Alunos;\nGerador de Relatórios;\nGerador de chamadas;\nServiços especializados de Funcionários comuns e Usuários administradores. \n<br>\n\nDesenvolvedores: Bruno Figueiredo Sousa, Lucas Luiz dos Santos, Rodrigo Leite do Sacramento.\n</html>\n");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 70, 710, 500);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundosobre.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
